### ISSUE TITLE
[Bug] CTD on last floor of treasure dungeons

### ISSUE THREAD

**Issue by Jaksuhn** [53m1k0l0n/FFXIV-LazyLoot#23]
I can reproduce this every time, provided I actually get to the end of a treasure dungeon. I believe it's whenever the second chest is open is what causes this instant CTD. Either LazyLoot doesn't support some of the loot in additional chests or the second chest confuses it. I'm not sure.

```
System.NullReferenceException: Object reference not set to an instance of an object.

   at LazyLoot.Commands.RollCommand.GetLastNotRolledItem() in D:\a\FFXIV-LazyLoot\FFXIV-LazyLoot\LazyLoot\Commands\RollCommand.cs:line 170

   at LazyLoot.Commands.RollCommand.Roll(String command, String arguments) in D:\a\FFXIV-LazyLoot\FFXIV-LazyLoot\LazyLoot\Commands\RollCommand.cs:line 47

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
This was the loot as it was shown when the crash happened.

![ffxiv_dx11_UHlE4FcQZq](https://user-images.githubusercontent.com/9527380/229245978-48e8bdee-57f1-4d8b-aaa4-d582400cef5f.png)

**Comment by 53m1k0l0n** [comment]
I think I know what the problem is, it looks like the plugin don't get the item data and I forgot a NullRef validation. 🤣
